services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dayquest-bot
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - stack.env
    restart: unless-stopped
    pull_policy: build
